### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by dcposch** [stevegury/jstack-profiler#7]
**i recommend creating a Github Release with the compiled jar file.**

jar files are portable--let's take advantage of that.

this tool looks very useful. thanks!

however, making every user compile it from scratch is a pain and a bad UX

```
$ <clone repo>
$ brew install sbt
<wait 5 mins>
$ cd jstack-profiler
```

```
$ sbt install
<...>
[info] Loading settings for project jstack-profiler-build from plugins.sbt ...
[info] Loading project definition from /Users/dc/code/jstack-profiler/project
[info] Updating ProjectRef(uri("file:/Users/dc/code/jstack-profiler/project/"), "jstack-profiler-build")...
[warn] 	module not found: com.eed3si9n#sbt-assembly;0.11.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.11.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.11.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/dc/.ivy2/local/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.11.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.12_1.0/0.11.2/sbt-assembly-0.11.2.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/dc/.sbt/preloaded/com.eed3si9n/sbt-assembly/0.11.2/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/dc/.sbt/preloaded/com/eed3si9n/sbt-assembly_2.12_1.0/0.11.2/sbt-assembly-0.11.2.pom
[warn] ==== artifactory: tried
[warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.11.2/ivys/ivy.xml
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.eed3si9n#sbt-assembly;0.11.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.eed3si9n:sbt-assembly:0.11.2 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.eed3si9n:sbt-assembly:0.11.2 (scalaVersion=2.12, sbtVersion=1.0) (/Users/dc/code/jstack-profiler/project/plugins.sbt#L3-4)
[warn] 		  +- default:jstack-profiler-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.11.2: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
```

**Comment by stevegury** [comment]
Hi @dcposch!

Thanks for the feedback, I created a [release](https://github.com/stevegury/jstack-profiler/releases/tag/v0.3) and also added a [script](https://github.com/stevegury/jstack-profiler#with-the-script) to simplify profiling a java process.

Best,
Steve

**Comment by dcposch** [comment]
sweet, thanks!!
